package com.dokcmonika90.retrophone

import android.app.Activity
import android.content.Intent
import android.graphics.*
import android.media.*
import android.os.Bundle
import android.util.SparseIntArray
import android.view.*
import android.widget.*
import java.util.zip.ZipInputStream
import kotlin.math.max

class MainActivity : Activity() {
    private external fun nativeVersion(): String
    private external fun nativeLoad(bytes: ByteArray): Boolean
    private external fun nativeReset()
    private external fun nativeFrame(): IntArray
    private external fun nativeRunFrame()
    private external fun nativeButtons(mask: Int)
    private external fun nativeAudio(): ShortArray
    private external fun nativeIsLoaded(): Boolean
    companion object { init { System.loadLibrary("retro_recompiler") } }
    private lateinit var screen: GameView
    private lateinit var status: TextView
    private lateinit var toolbar: LinearLayout
    private var audio: AudioTrack?=null
    private var running=false
    private var audioRunning=false
    private var gameplayFullscreen=false
    private val frameMs=16L
    private val activeTouches=SparseIntArray()
    private val libraryPrefs by lazy{getSharedPreferences("rom_library",MODE_PRIVATE)}
    private val romDirectory by lazy{java.io.File(filesDir,"roms").apply{mkdirs()}}
    override fun onCreate(state:Bundle?){super.onCreate(state);window.setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);requestedOrientation=android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;enterImmersiveUi();screen=GameView();val root=FrameLayout(this).apply{setBackgroundColor(Color.BLACK)};root.addView(screen,FrameLayout.LayoutParams(-1,-1).apply{topMargin=dp(62)});toolbar=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;setPadding(dp(8),dp(4),dp(8),dp(4));setBackgroundColor(0xCC101010.toInt());elevation=dp(4).toFloat()};val load=Button(this).apply{text="LOAD NES";setOnClickListener{pickRom()}};val library=Button(this).apply{text="LIBRARY";setOnClickListener{showLibrary()}};val reset=Button(this).apply{text="RESET";setOnClickListener{nativeReset();status.text="  Reset";screen.invalidate()}};val fullscreen=Button(this).apply{text="FULLSCREEN";setOnClickListener{setGameplayFullscreen(!gameplayFullscreen)}};status=TextView(this).apply{text="  ${nativeVersion()}";setTextColor(Color.WHITE);textSize=13f;gravity=Gravity.CENTER_VERTICAL;maxLines=2};toolbar.addView(load);toolbar.addView(library);toolbar.addView(reset);toolbar.addView(fullscreen);toolbar.addView(status,LinearLayout.LayoutParams(0,-1,1f));root.addView(toolbar,FrameLayout.LayoutParams(-1,dp(62),Gravity.TOP));setContentView(root);startAudio();startLoop()}
    private fun dp(v:Int)= (v*resources.displayMetrics.density+0.5f).toInt()
    private fun enterImmersiveUi(){window.decorView.systemUiVisibility=View.SYSTEM_UI_FLAG_FULLSCREEN or View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY or View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN or View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or View.SYSTEM_UI_FLAG_LAYOUT_STABLE}
    private fun setGameplayFullscreen(f:Boolean){gameplayFullscreen=f;toolbar.visibility=if(f)View.GONE else View.VISIBLE;val p=screen.layoutParams as FrameLayout.LayoutParams;p.topMargin=if(f)0 else dp(62);screen.layoutParams=p;status.text=if(nativeIsLoaded()){if(f)"  Fullscreen gameplay" else "  Gameplay controls visible"}else{if(f)"  Fullscreen — tap BACK to exit" else "  ${nativeVersion()}"};enterImmersiveUi();screen.invalidate()}
    override fun onWindowFocusChanged(h:Boolean){super.onWindowFocusChanged(h);if(h)enterImmersiveUi()}
    override fun onBackPressed(){if(gameplayFullscreen)setGameplayFullscreen(false)else super.onBackPressed()}
    private fun pickRom(){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="*/*";addCategory(Intent.CATEGORY_OPENABLE);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION)},42)}
    private fun validHeader(b:ByteArray)=b.size>=16&&b[0].toInt()=='N'.code&&b[1].toInt()=='E'.code&&b[2].toInt()=='S'.code&&b[3].toInt()==0x1A
    private fun unwrapRom(d:ByteArray):Pair<ByteArray,String>?{if(validHeader(d))return d to "NES ROM";if(d.size>=4&&d[0].toInt()==0x50&&d[1].toInt()==0x4b)ZipInputStream(d.inputStream()).use{z->var e=z.nextEntry;while(e!=null){if(!e.isDirectory&&e.name.lowercase().endsWith(".nes")){val r=z.readBytes();if(validHeader(r))return r to e.name};e=z.nextEntry}};return null}
    private fun libraryFile(b:ByteArray)=java.io.File(romDirectory,"rom_${Integer.toHexString(b.contentHashCode())}.nes")
    private fun saveToLibrary(b:ByteArray,n:String){try{val f=libraryFile(b);f.writeBytes(b);libraryPrefs.edit().putString("name_${f.name}",n.substringAfterLast('/')).putString("last_rom",f.name).apply()}catch(_:Exception){}}
    private fun showLibrary(){val fs=romDirectory.listFiles{f->f.isFile&&f.extension.equals("nes",true)}?.sortedByDescending{it.lastModified()}?:emptyList();val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(8),dp(18),dp(8))};if(fs.isEmpty())box.addView(TextView(this).apply{text="No games saved yet.\nUse LOAD NES to add a game.";textSize=17f;setPadding(0,dp(16),0,dp(16))})else fs.forEach{f->val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};val n=libraryPrefs.getString("name_${f.name}",f.name)?:f.name;val label=TextView(this).apply{text=n;textSize=16f;setPadding(0,dp(8),dp(8),dp(8))};val play=Button(this).apply{text="PLAY"};play.setOnClickListener{loadRomBytes(f.readBytes(),n,false);f.setLastModified(System.currentTimeMillis());showLibrary()};val del=Button(this).apply{text="DELETE"};del.setOnClickListener{f.delete();libraryPrefs.edit().remove("name_${f.name}").apply();showLibrary()};row.addView(label,LinearLayout.LayoutParams(0,-2,1f));row.addView(play);row.addView(del);box.addView(row)};AlertDialog.Builder(this).setTitle("ROM Library").setView(box).setNegativeButton("CLOSE",null).show()}
    private fun loadRomBytes(b:ByteArray,n:String,save:Boolean){val m=if(b.size>=8)((b[6].toInt() and 0xF0)shr 4)or(b[7].toInt()and 0xF0)else -1;try{if(save)saveToLibrary(b,n);if(nativeLoad(b)){nativeReset();status.text="  ROM loaded: $n (Mapper $m, ${b.size/1024} KB)";screen.invalidate()}else{status.text="  Mapper $m is not implemented by the current core";Toast.makeText(this,"LaiNES could not load Mapper $m",Toast.LENGTH_LONG).show()}}catch(e:Exception){status.text="  ROM load failed";Toast.makeText(this,"ROM load failed: ${e.message?:"unknown error"}",Toast.LENGTH_LONG).show()}}
    override fun onActivityResult(q:Int,r:Int,d:Intent?){super.onActivityResult(q,r,d);if(q!=42||r!=RESULT_OK||d?.data==null)return;try{val u=d.data!!;try{contentResolver.takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION)}catch(_:Exception){};val raw=contentResolver.openInputStream(u)?.use{it.readBytes()};if(raw==null){status.text="  ROM could not be read";return};val x=unwrapRom(raw);if(x==null){status.text="  Unsupported ROM wrapper";Toast.makeText(this,"No valid .nes ROM was found in that file",Toast.LENGTH_LONG).show();return};loadRomBytes(x.first,x.second,true)}catch(e:Exception){status.text="  ROM load failed";Toast.makeText(this,"ROM load failed: ${e.message?:"unknown error"}",Toast.LENGTH_LONG).show()}}
    private fun startAudio(){if(audioRunning)return;try{val sr=44100;val min=AudioTrack.getMinBufferSize(sr,AudioFormat.CHANNEL_OUT_MONO,AudioFormat.ENCODING_PCM_16BIT);if(min<=0)throw IllegalStateException("AudioTrack buffer size unavailable");audio=AudioTrack.Builder().setAudioAttributes(AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_GAME).setContentType(AudioAttributes.CONTENT_TYPE_MUSIC).build()).setAudioFormat(AudioFormat.Builder().setSampleRate(sr).setEncoding(AudioFormat.ENCODING_PCM_16BIT).setChannelMask(AudioFormat.CHANNEL_OUT_MONO).build()).setBufferSizeInBytes(max(min,sr/4*2)).setTransferMode(AudioTrack.MODE_STREAM).build();audio?.play();audioRunning=true;Thread{while(audioRunning&&!isFinishing){try{val p=nativeAudio();if(p.isNotEmpty())audio?.write(p,0,p.size,AudioTrack.WRITE_BLOCKING)else Thread.sleep(2)}catch(_:InterruptedException){break}catch(e:Exception){runOnUiThread{status.text="  Audio error: ${e.message?:"unknown"}"};break}}}.start()}catch(e:Exception){audioRunning=false;status.text="  Audio unavailable: ${e.message?:"unknown"}"}}
    private fun startLoop(){running=true;Thread{while(running&&!isFinishing){val s=System.nanoTime();if(nativeIsLoaded())nativeRunFrame();runOnUiThread{screen.invalidate()};val sl=frameMs-(System.nanoTime()-s)/1000000L;if(sl>0)Thread.sleep(sl)}}.start()}
    private fun controlMaskAt(x:Float,y:Float):Int{val w=screen.width.toFloat().coerceAtLeast(1f);val h=screen.height.toFloat().coerceAtLeast(1f);val r=minOf(w,h)*.105f;val dcx=w*.16f;val dcy=h*.77f;val ax=w*.84f;val ay=h*.77f;val bx=w*.72f;val by=h*.86f;fun inC(px:Float,py:Float,rr:Float):Boolean{val dx=x-px;val dy=y-py;return dx*dx+dy*dy<=rr*rr};val dr=r*.72f;var m=0;if(inC(dcx,dcy-r*1.05f,dr))m=m or 8;if(inC(dcx,dcy+r*1.05f,dr))m=m or 4;if(inC(dcx-r*1.05f,dcy,dr))m=m or 2;if(inC(dcx+r*1.05f,dcy,dr))m=m or 1;if(m!=0)return m;if(inC(ax,ay,r*1.05f))return 16;if(inC(bx,by,r*.95f))return 32;if(x>=w*.39f&&x<=w*.51f&&y>=h*.82f&&y<=h*.96f)return 64;if(x>=w*.51f&&x<=w*.63f&&y>=h*.82f&&y<=h*.96f)return 128;return 0}
    private fun refreshTouchMask(){var m=0;for(i in 0 until activeTouches.size())m=m or activeTouches.valueAt(i);nativeButtons(m);screen.invalidate()}
    override fun dispatchTouchEvent(e:MotionEvent):Boolean{val a=e.actionMasked;val th=if(gameplayFullscreen)0f else dp(62).toFloat();if(e.y<th&&activeTouches.size()==0)return super.dispatchTouchEvent(e);when(a){MotionEvent.ACTION_DOWN->{activeTouches.clear();activeTouches.put(e.getPointerId(0),controlMaskAt(e.getX(0),e.getY(0)));refreshTouchMask();return true};MotionEvent.ACTION_POINTER_DOWN->{val i=e.actionIndex;activeTouches.put(e.getPointerId(i),controlMaskAt(e.getX(i),e.getY(i)));refreshTouchMask();return true};MotionEvent.ACTION_MOVE->{for(i in 0 until e.pointerCount)activeTouches.put(e.getPointerId(i),controlMaskAt(e.getX(i),e.getY(i)));refreshTouchMask();return true};MotionEvent.ACTION_POINTER_UP->{val i=e.actionIndex;activeTouches.delete(e.getPointerId(i));for(j in 0 until e.pointerCount)if(j!=i)activeTouches.put(e.getPointerId(j),controlMaskAt(e.getX(j),e.getY(j)));refreshTouchMask();return true};MotionEvent.ACTION_UP,MotionEvent.ACTION_CANCEL->{activeTouches.clear();nativeButtons(0);screen.invalidate();return true}};return true}
    inner class GameView:View(this){private val paint=Paint(Paint.FILTER_BITMAP_FLAG);private val bitmap=Bitmap.createBitmap(256,240,Bitmap.Config.ARGB_8888);init{isClickable=true;isFocusable=true;isFocusableInTouchMode=true};override fun onDraw(c:Canvas){val p=nativeFrame();if(p.size==256*240)bitmap.setPixels(p,0,256,0,0,256,240);c.drawColor(Color.BLACK);val iscale=minOf(width/256,height/240);val scale=if(iscale>=1)iscale.toFloat() else minOf(width/256f,height/240f);val dw=256f*scale;val dh=240f*scale;val l=(width-dw)/2f;val t=(height-dh)/2f;c.drawBitmap(bitmap,null,RectF(l,t,l+dw,t+dh),paint);drawControls(c)};private fun drawControls(c:Canvas){val w=width.toFloat();val h=height.toFloat();val r=minOf(w,h)*.105f;val dcx=w*.16f;val dcy=h*.77f;val ax=w*.84f;val ay=h*.77f;val bx=w*.72f;val by=h*.86f;paint.style=Paint.Style.FILL;paint.alpha=145;paint.color=Color.WHITE;c.drawCircle(dcx,dcy,r,paint);c.drawCircle(dcx-r*1.05f,dcy,r*.55f,paint);c.drawCircle(dcx+r*1.05f,dcy,r*.55f,paint);c.drawCircle(dcx,dcy-r*1.05f,r*.55f,paint);c.drawCircle(dcx,dcy+r*1.05f,r*.55f,paint);c.drawCircle(ax,ay,r,paint);c.drawCircle(bx,by,r*.9f,paint);paint.textAlign=Paint.Align.CENTER;paint.textSize=r*.55f;paint.color=Color.DKGRAY;paint.alpha=230;c.drawText("A",ax,ay+r*.2f,paint);c.drawText("B",bx,by+r*.2f,paint);paint.alpha=145;paint.color=Color.WHITE;c.drawRoundRect(RectF(w*.39f,h*.82f,w*.51f,h*.96f),16f,16f,paint);c.drawRoundRect(RectF(w*.51f,h*.82f,w*.63f,h*.96f),16f,16f,paint);paint.color=Color.DKGRAY;paint.alpha=230;paint.textSize=r*.38f;c.drawText("SELECT",w*.45f,h*.90f,paint);c.drawText("START",w*.57f,h*.90f,paint);var held=0;for(i in 0 until activeTouches.size())held=held or activeTouches.valueAt(i);paint.color=Color.YELLOW;paint.alpha=210;if((held and 8)!=0)c.drawCircle(dcx,dcy-r*1.05f,r*.56f,paint);if((held and 4)!=0)c.drawCircle(dcx,dcy+r*1.05f,r*.56f,paint);if((held and 2)!=0)c.drawCircle(dcx-r*1.05f,dcy,r*.56f,paint);if((held and 1)!=0)c.drawCircle(dcx+r*1.05f,dcy,r*.56f,paint);if((held and 16)!=0)c.drawCircle(ax,ay,r*.88f,paint);if((held and 32)!=0)c.drawCircle(bx,by,r*.78f,paint);if((held and 64)!=0)c.drawRoundRect(RectF(w*.39f,h*.82f,w*.51f,h*.96f),16f,16f,paint);if((held and 128)!=0)c.drawRoundRect(RectF(w*.51f,h*.82f,w*.63f,h*.96f),16f,16f,paint)};override fun onTouchEvent(e:MotionEvent)=true}
    override fun onDestroy(){running=false;audioRunning=false;activeTouches.clear();nativeButtons(0);try{audio?.pause()}catch(_:Exception){};try{audio?.flush()}catch(_:Exception){};try{audio?.release()}catch(_:Exception){};super.onDestroy()}
}
